New glue vernacular command
PrincetonUniversity/certicoq pull request #28
Opened 2020-12-22 05:00 UTC by joom

```
CertiCoq Generate Glue -file "filename" [nat, list, bool].
```
creates `filename.c` and `filename.h` with the glue code for the types listed above. It also works with programs if the user wants to use it that way:
```
CertiCoq Generate Glue -file "filename" [negb].
```
This command creates files that have glue code for the `bool` type.

The `CertiCoq Compile` command still creates `glue.*.{c,h}` files automatically for compiled programs, I'm assuming @zoep doesn't want that, but I wanted to check before I delete that and fix the tests accordingly, hence I didn't push into `clean` automatically and created a PR instead.

2020-12-22 20:26 UTC, zoep requested changes

2020-12-22 20:26 UTC, zoep commented on theories/Compiler/pipeline.v
> -Definition make_glue (opts : Options) (p : Template.Ast.program)
Seems that this should be now moved to glue.v instead?

2020-12-22 23:58 UTC, joom commented on theories/Compiler/pipeline.v
> -Definition make_glue (opts : Options) (p : Template.Ast.program)
Good point. Just did that in commit 79eaf9b.

2020-12-23 00:29 UTC, merged

2020-12-23 00:29 UTC, zoep commented
Awesome, thanks!